"""remove_examples_table

Revision ID: accb92f574da
Revises: 29b8373ce09a
Create Date: 2025-05-14 11:40:18.970013+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accb92f574da'
down_revision = '29b8373ce09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examples')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examples',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='examples_pkey')
    )
    # ### end Alembic commands ###
