"""update_workspace_team_ids_to_array

Revision ID: 99729e712339
Revises: 20250520_105800
Create Date: 2025-06-19 23:51:03.971812+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99729e712339'
down_revision = '20250520_105800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permits', 'update_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_permits_workspace_id', table_name='permits')
    op.add_column('workspaces', sa.Column('team_ids', sa.ARRAY(sa.String()), nullable=True))
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('team_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'workspaces', 'teams', ['team_id'], ['id'])
    op.drop_column('workspaces', 'team_ids')
    op.create_index('ix_permits_workspace_id', 'permits', ['workspace_id'], unique=False)
    op.alter_column('permits', 'update_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
