"""Create database models

Revision ID: 29b8373ce09a
Revises: 
Create Date: 2025-05-14 11:29:50.173511+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b8373ce09a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org_city', sa.String(), nullable=True),
    sa.Column('org_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_org_name'), 'organizations', ['org_name'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('team_contact_name', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_team_name'), 'teams', ['team_name'], unique=False)
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_search', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('cohort_builder', sa.Integer(), nullable=True),
    sa.Column('data_quality', sa.Integer(), nullable=True),
    sa.Column('export', sa.Integer(), nullable=True),
    sa.Column('results_report', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_types_id'), 'user_types', ['id'], unique=False)
    op.create_table('permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_name', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('(utcnow())'), nullable=True),
    sa.Column('validity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permits_id'), 'permits', ['id'], unique=False)
    op.create_index(op.f('ix_permits_permit_name'), 'permits', ['permit_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('user_teams',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('(utcnow())'), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('last_edit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_search', sa.Integer(), nullable=True),
    sa.Column('data_access', sa.Integer(), nullable=True),
    sa.Column('data_query', sa.String(), nullable=True),
    sa.Column('result_report', sa.Integer(), nullable=True),
    sa.Column('vr_study_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('(utcnow())'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('running_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_analysis_name'), 'analyses', ['analysis_name'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('metadata_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(utcnow())'), nullable=True),
    sa.Column('shared', sa.String(), nullable=True),
    sa.Column('type_cancer', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_searches_id'), 'metadata_searches', ['id'], unique=False)
    op.create_table('workspace_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(utcnow())'), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_histories_id'), 'workspace_histories', ['id'], unique=False)
    op.create_table('algorithms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('(utcnow())'), nullable=True),
    sa.Column('version_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input', sa.String(), nullable=True),
    sa.Column('output', sa.String(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithms_id'), 'algorithms', ['id'], unique=False)
    op.create_index(op.f('ix_algorithms_method_name'), 'algorithms', ['method_name'], unique=False)
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_name', sa.String(), nullable=True),
    sa.Column('cohort_description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('(utcnow())'), nullable=True),
    sa.Column('version_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohorts_cohort_name'), 'cohorts', ['cohort_name'], unique=False)
    op.create_index(op.f('ix_cohorts_id'), 'cohorts', ['id'], unique=False)
    op.create_table('cohort_algorithms',
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('algorithm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('cohort_id', 'algorithm_id')
    )
    op.create_table('cohort_results',
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('data_id', 'cohort_id')
    )
    op.create_index(op.f('ix_cohort_results_data_id'), 'cohort_results', ['data_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohort_results_data_id'), table_name='cohort_results')
    op.drop_table('cohort_results')
    op.drop_table('cohort_algorithms')
    op.drop_index(op.f('ix_cohorts_id'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_cohort_name'), table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index(op.f('ix_algorithms_method_name'), table_name='algorithms')
    op.drop_index(op.f('ix_algorithms_id'), table_name='algorithms')
    op.drop_table('algorithms')
    op.drop_index(op.f('ix_workspace_histories_id'), table_name='workspace_histories')
    op.drop_table('workspace_histories')
    op.drop_index(op.f('ix_metadata_searches_id'), table_name='metadata_searches')
    op.drop_table('metadata_searches')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_analysis_name'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('user_teams')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_permits_permit_name'), table_name='permits')
    op.drop_index(op.f('ix_permits_id'), table_name='permits')
    op.drop_table('permits')
    op.drop_index(op.f('ix_user_types_id'), table_name='user_types')
    op.drop_table('user_types')
    op.drop_index(op.f('ix_teams_team_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_organizations_org_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
