apiVersion: v1
kind: Secret
metadata:
  name: raven-api-secrets
  namespace: raven-api
type: Opaque
stringData:
  database-uri: "postgresql://raven_user:raven_password@postgres-service:5432/raven_db"
  # openssl rand -hex 32
  secret-key: "40bfa3453e21644b34e4291ed47ad84aa4b5da36538b1532aef0c689e41227ef"
  postgres-user: "raven_user"
  postgres-password: "raven_password"
  postgres-db: "raven_db"
  keycloak-client-secret: "EfesLqjtooH49AYUU2U4ZkJKfQGFuUwx"
  keycloak-public-key: |-
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYFZDgztv/r9/mSvoGbW5o8P+ACjWI4Drzz0E551hWOXe6XIQ+zTTLYjhFQVGSlhE2hEsOaJwATyjFKk+/rHKAAOMGqpFv1qeqCOVuczuJs2tTnbEFdDAYHko60Os+oNCDHKVh+YI8+/zm/XXMMCj2uDQXgs2y08zjrTqcpt3TsMbgaXL1+m7HU440crVBJQNUv2lvI8rhRFVKMWCVsE7aGq2aavUaM3ITFB4Hw6YiT3P8K1cQvBhwwFNboEJ7LEEimtHVkL57Lgfup7au/TXCkDg9og/b1simjT53gqFIXRH8CenQ0O1mucm7440p8Ma+ZjLx3lUAyNYqPn55YFBQIDAQAB
  # Telemetry configuration
  enable-telemetry: "true"
  telemetry-endpoint: "http://jaeger-collector.monitoring.svc.cluster.local:4317"
  telemetry-sampling-rate: "1.0"
  # Prometheus configuration
  enable-prometheus: "true"
  metrics-port: "8000"
