apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: raven-api-tls-staging
  namespace: istio-system
spec:
  # Nombre del secreto donde se almacenará el certificado
  secretName: raven-api-tls-staging-secret
  
  # Configuración del certificado
  issuerRef:
    name: letsencrypt-staging  # Usar el ClusterIssuer de staging primero
    kind: ClusterIssuer
    group: cert-manager.io
  
  # Dominio para el certificado
  dnsNames:
  - orchestrator.idea.lst.tfo.upm.es
  
  # Configuración adicional
  duration: 2160h  # 90 días
  renewBefore: 360h  # Renovar 15 días antes de expirar
  
  # Uso del certificado
  usages:
  - digital signature
  - key encipherment
