apiVersion: apps/v1
kind: Deployment
metadata:
  name: raven-api
  labels:
    app: raven-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raven-api
      version: v1
  template:
    metadata:
      labels:
        app: raven-api
        version: v1
      annotations:
        sidecar.istio.io/inject: "true" # Enable Istio sidecar injection
    spec:
      containers:
      - name: raven-api
        image: raven-api:latest # Adjust according to your container registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: raven-api-secrets
              key: database-uri
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: raven-api-secrets
              key: secret-key
        readinessProbe:
          httpGet:
            path: /raven-api/v1/health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
