apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: override-csp-header
  namespace: default
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        response_headers_to_remove:
        - "content-security-policy"
        - "Content-Security-Policy"
        - "CONTENT-SECURITY-POLICY"
        response_headers_to_add:
        - header:
            key: "Content-Security-Policy"
            value: "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; frame-src *; connect-src *; font-src *; style-src * 'unsafe-inline'; img-src *; script-src * 'unsafe-inline' 'unsafe-eval';"
          append: false
