apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: raven-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  # HTTP - redirige a HTTPS
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "orchestrator.idea.lst.tfo.upm.es"
    - "vantage.orchestrator.idea.lst.tfo.upm.es"
    - "pgadmin.orchestrator.idea.lst.tfo.upm.es"
    - "jaeger.orchestrator.idea.lst.tfo.upm.es"
    - "prometheus.orchestrator.idea.lst.tfo.upm.es"
    - "grafana.orchestrator.idea.lst.tfo.upm.es"
    tls:
      httpsRedirect: true
  # HTTPS - certificado válido
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "orchestrator.idea.lst.tfo.upm.es"
    - "vantage.orchestrator.idea.lst.tfo.upm.es"
    - "pgadmin.orchestrator.idea.lst.tfo.upm.es"
    - "jaeger.orchestrator.idea.lst.tfo.upm.es"
    - "prometheus.orchestrator.idea.lst.tfo.upm.es"
    - "grafana.orchestrator.idea.lst.tfo.upm.es"
    tls:
      mode: SIMPLE
      credentialName: raven-api-tls-secret
