apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: raven-api-vs
  namespace: default
spec:
  hosts:
  - "orchestrator.idea.lst.tfo.upm.es"
  - "138.4.10.238"
  gateways:
  - raven-gateway
  http:
  # Manejar peticiones OPTIONS para CORS preflight
  - match:
    - uri:
        prefix: /server
      method:
        exact: OPTIONS
    route:
    - destination:
        host: vantage6server-vantage6-server-service.default.svc.cluster.local
        port:
          number: 7601
      headers:
        response:
          remove:
          - "Access-Control-Allow-Origin"
          add:
            Access-Control-Allow-Origin: "*"
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
            Access-Control-Allow-Headers: "Content-Type, Authorization, X-Requested-With"
            Access-Control-Max-Age: "86400"
  - match:
    - uri:
        prefix: /socket.io
      method:
        exact: OPTIONS
    route:
    - destination:
        host: vantage6server-vantage6-server-service.default.svc.cluster.local
        port:
          number: 7601
      headers:
        response:
          remove:
          - "Access-Control-Allow-Origin"
          add:
            Access-Control-Allow-Origin: "*"
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
            Access-Control-Allow-Headers: "Content-Type, Authorization, X-Requested-With"
            Access-Control-Max-Age: "86400"
  - match:
    - uri:
        prefix: /raven-api
    route:
    - destination:
        host: raven-api.raven-api.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /docs
    route:
    - destination:
        host: raven-api.raven-api.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /server
    route:
    - destination:
        host: vantage6server-vantage6-server-service.default.svc.cluster.local
        port:
          number: 7601
      headers:
        response:
          remove:
          - "Access-Control-Allow-Origin"
          add:
            Access-Control-Allow-Origin: "*"
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
            Access-Control-Allow-Headers: "Content-Type, Authorization, X-Requested-With"
  - match:
    - uri:
        prefix: /socket.io
    route:
    - destination:
        host: vantage6server-vantage6-server-service.default.svc.cluster.local
        port:
          number: 7601
      headers:
        response:
          remove:
          - "Access-Control-Allow-Origin"
          add:
            Access-Control-Allow-Origin: "*"
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
            Access-Control-Allow-Headers: "Content-Type, Authorization, X-Requested-With"
  - match:
    - uri:
        prefix: /store
    route:
    - destination:
        host: vantage6store-store-service.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: vantage6server-vantage6-frontend-service.default.svc.cluster.local
        port:
          number: 7600
      headers:
        response:
          remove:
          - "content-security-policy"
          - "Content-Security-Policy"
          add:
            Content-Security-Policy: "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; frame-src *; connect-src *; font-src *; style-src * 'unsafe-inline'; img-src *; script-src * 'unsafe-inline' 'unsafe-eval';"
