apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: raven-api-vs
  namespace: default
spec:
  hosts:
  - "orchestrator.idea.lst.tfo.upm.es"
  - "138.4.10.238"
  gateways:
  - raven-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: raven-api.${NAMESPACE}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /ui
    rewrite:
      uri: /
    route:
    - destination:
        host: vantage6server-vantage6-frontend-service.default.svc.cluster.local
        port:
          number: 7600
  - match:
    - uri:
        prefix: /server
    route:
    - destination:
        host: vantage6server-vantage6-server-service.default.svc.cluster.local
        port:
          number: 7601
  - match:
    - uri:
        prefix: /store
    route:
    - destination:
        host: vantage6store-store-service.default.svc.cluster.local
        port:
          number: 80
