apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: raven-api
spec:
  hosts:
  - "host02.idea.lst.tfo.upm.es"
  - "138.4.10.238"
  gateways:
  - raven-gateway
  http:
  - match:
    - uri:
        prefix: /raven-api
    route:
    - destination:
        host: raven-api
        port:
          number: 80
