apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: raven-api-vs
  namespace: default
spec:
  hosts:
  - "orchestrator.idea.lst.tfo.upm.es"
  - "pgadmin.orchestrator.idea.lst.tfo.upm.es"
  - "jaeger.orchestrator.idea.lst.tfo.upm.es"
  - "prometheus.orchestrator.idea.lst.tfo.upm.es"
  - "grafana.orchestrator.idea.lst.tfo.upm.es"
  gateways:
  - raven-gateway
  http:
  # Dominio base: mantener rutas por path
  - match:
    - headers:
        Host:
          exact: orchestrator.idea.lst.tfo.upm.es
      uri:
        prefix: /raven-api
    route:
    - destination:
        host: raven-api.raven-api.svc.cluster.local
        port:
          number: 80
  - match:
    - headers:
        Host:
          exact: orchestrator.idea.lst.tfo.upm.es
      uri:
        prefix: /docs
    route:
    - destination:
        host: raven-api.raven-api.svc.cluster.local
        port:
          number: 80
  - match:
    - headers:
        Host:
          exact: orchestrator.idea.lst.tfo.upm.es
      uri:
        prefix: /server
    route:
    - destination:
        host: vantage6server-vantage6-server-service.default.svc.cluster.local
        port:
          number: 7601
      headers:
        response:
          remove:
          - "Access-Control-Allow-Origin"
          add:
            Access-Control-Allow-Origin: "https://idea4rc.kube.franky.codes"
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
            Access-Control-Allow-Headers: "Content-Type, Authorization, X-Requested-With"
            Access-Control-Allow-Credentials: "true"
  - match:
    - headers:
        Host:
          exact: orchestrator.idea.lst.tfo.upm.es
      uri:
        prefix: /socket.io
    route:
    - destination:
        host: vantage6server-vantage6-server-service.default.svc.cluster.local
        port:
          number: 7601
      headers:
        response:
          remove:
          - "Access-Control-Allow-Origin"
          add:
            Access-Control-Allow-Origin: "https://idea4rc.kube.franky.codes"
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
            Access-Control-Allow-Headers: "Content-Type, Authorization, X-Requested-With"
            Access-Control-Allow-Credentials: "true"
  - match:
    - headers:
        Host:
          exact: orchestrator.idea.lst.tfo.upm.es
      uri:
        prefix: /store
    route:
    - destination:
        host: vantage6store-store-service.default.svc.cluster.local
        port:
          number: 80
  - match:
    - headers:
        Host:
          exact: orchestrator.idea.lst.tfo.upm.es
      uri:
        prefix: /
    route:
    - destination:
        host: vantage6server-vantage6-frontend-service.default.svc.cluster.local
        port:
          number: 7600
      headers:
        response:
          remove:
          - "content-security-policy"
          - "Content-Security-Policy"
          add:
            Content-Security-Policy: "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; frame-src *; connect-src *; font-src *; style-src * 'unsafe-inline'; img-src *; script-src * 'unsafe-inline' 'unsafe-eval';"
  # PGAdmin en subdominio
  - match:
    - headers:
        Host:
          exact: pgadmin.orchestrator.idea.lst.tfo.upm.es
    route:
    - destination:
        host: pgadmin-service.raven-api.svc.cluster.local
        port:
          number: 80
  # Jaeger en subdominio
  - match:
    - headers:
        Host:
          exact: jaeger.orchestrator.idea.lst.tfo.upm.es
    route:
    - destination:
        host: jaeger-service.monitoring.svc.cluster.local
        port:
          number: 16686
  # Prometheus en subdominio
  - match:
    - headers:
        Host:
          exact: prometheus.orchestrator.idea.lst.tfo.upm.es
    route:
    - destination:
        host: prometheus-service.monitoring.svc.cluster.local
        port:
          number: 9090
  # Grafana en subdominio
  - match:
    - headers:
        Host:
          exact: grafana.orchestrator.idea.lst.tfo.upm.es
    route:
    - destination:
        host: grafana-service.monitoring.svc.cluster.local
        port:
          number: 3000
