apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../

patchesStrategicMerge:
- deployment-patch.yaml
- secrets-patch.yaml

replicas:
- name: raven-api
  count: 3
- name: postgres
  count: 1

images:
- name: localhost:32000/raven-api
  newName: your-registry.com/raven-api
  newTag: v1.0.0
